const { getCallbackBranch } = require("../response/responceDto");

const exceljs = require("exceljs");

const excel = {
    excelGen: async (req, res) => {
        const workbook = new exceljs.Workbook();
        const workSheet = await workbook.xlsx.readFile("services/pay.xlsx");
        
        let rows;

        let mokData = [ { in_date: '202111',
        emp_no: 208,
        emp_name_kr: '이호완',
        emp_identi: '520925-1775017',
        position_name: '정규기사',
        emp_stt_date: '2014-10-13',
        vehicle_license_no: 27312136,
        vehicle_license_req_no: '대구31바2136',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 34,
        meter_charge: 1122000,
        biz_dist: 756,
        biz_time: 34.15,
        meter_charge_time: 30.2,
        biz_dist_time: 27.5,
        dispatcher_cnt: 3,
        base_pay: 296480,
        year_of_service: 7,
        year_of_service_pay: 14000,
        weekly_cnt: 0,
        weekly_pay: 0,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 1167066,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 40030,
        care_insurance: 9220,
        employment_insurance: 2484,
        advance_payment: 1122000,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 310480,
        total_deduction: 1173734,
        total_salary: -863254 },
      { in_date: '202111',
        emp_no: 184,
        emp_name_kr: '신병만',
        emp_identi: '630110-1780824',
        position_name: '정규기사',
        emp_stt_date: '2014-02-17',
        vehicle_license_no: 27312129,
        vehicle_license_req_no: '대구31바2129',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 133,
        meter_charge: 4346600,
        biz_dist: 3147,
        biz_time: 130.19,
        meter_charge_time: 116.9,
        biz_dist_time: 114.4,
        dispatcher_cnt: 4,
        base_pay: 1159760,
        year_of_service: 7,
        year_of_service_pay: 14000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 605970,
        remuneration_amount: 838867,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 37120,
        health_insurance: 28770,
        care_insurance: 6620,
        employment_insurance: 16151,
        advance_payment: 4346600,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 2018903,
        total_deduction: 4435261,
        total_salary: -2416358 },
      { in_date: '202111',
        emp_no: 207,
        emp_name_kr: '석종현',
        emp_identi: '580720-1696911',
        position_name: '정규기사',
        emp_stt_date: '2014-10-01',
        vehicle_license_no: 27317325,
        vehicle_license_req_no: '대구31바7325',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 69,
        meter_charge: 2396300,
        biz_dist: 1774,
        biz_time: 59.53,
        meter_charge_time: 64.5,
        biz_dist_time: 64.5,
        dispatcher_cnt: 25,
        base_pay: 601680,
        year_of_service: 7,
        year_of_service_pay: 14000,
        weekly_cnt: 0,
        weekly_pay: 0,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 600686,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 20600,
        care_insurance: 4740,
        employment_insurance: 4925,
        advance_payment: 2396300,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 615680,
        total_deduction: 2426565,
        total_salary: -1810885 },
      { in_date: '202111',
        emp_no: 209,
        emp_name_kr: '여홍대',
        emp_identi: '691007-1690811',
        position_name: '정규기사',
        emp_stt_date: '2015-01-28',
        vehicle_license_no: 27317301,
        vehicle_license_req_no: '대구31바7301',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 138,
        meter_charge: 4657900,
        biz_dist: 3308,
        biz_time: 130.3,
        meter_charge_time: 125.3,
        biz_dist_time: 120.3,
        dispatcher_cnt: 26,
        base_pay: 1203360,
        year_of_service: 6,
        year_of_service_pay: 12000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 1,
        holiday_pay: 59794,
        bonus: 746055,
        remuneration_amount: 1105079,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 48870,
        health_insurance: 37900,
        care_insurance: 8720,
        employment_insurance: 18083,
        advance_payment: 4657900,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 2260382,
        total_deduction: 4771473,
        total_salary: -2511091 },
      { in_date: '202111',
        emp_no: 212,
        emp_name_kr: '남재원',
        emp_identi: '580724-1790411',
        position_name: '정규기사',
        emp_stt_date: '2016-04-12',
        vehicle_license_no: 27312121,
        vehicle_license_req_no: '대구31바2121',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 94,
        meter_charge: 3388900,
        biz_dist: 2493,
        biz_time: 99.8,
        meter_charge_time: 91.2,
        biz_dist_time: 90.6,
        dispatcher_cnt: 27,
        base_pay: 819680,
        year_of_service: 5,
        year_of_service_pay: 10000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 175005,
        remuneration_amount: 681208,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 23360,
        care_insurance: 5380,
        employment_insurance: 9951,
        advance_payment: 3388900,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1243858,
        total_deduction: 3427591,
        total_salary: -2183733 },
      { in_date: '202111',
        emp_no: 217,
        emp_name_kr: '김태원',
        emp_identi: '530208-1773312',
        position_name: '정규기사',
        emp_stt_date: '2017-07-01',
        vehicle_license_no: 27317346,
        vehicle_license_req_no: '대구31바7346',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 57,
        meter_charge: 1862400,
        biz_dist: 1430,
        biz_time: 52.58,
        meter_charge_time: 50.1,
        biz_dist_time: 52,
        dispatcher_cnt: 3,
        base_pay: 497040,
        year_of_service: 4,
        year_of_service_pay: 8000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 894462,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 30680,
        care_insurance: 7060,
        employment_insurance: 5954,
        advance_payment: 1862400,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 744213,
        total_deduction: 1906094,
        total_salary: -1161881 },
      { in_date: '202111',
        emp_no: 201,
        emp_name_kr: '류지봉',
        emp_identi: '561119-1798113',
        position_name: '정규기사',
        emp_stt_date: '2017-12-01',
        vehicle_license_no: 27317346,
        vehicle_license_req_no: '대구31바7346',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 1,
        meter_charge: 47900,
        biz_dist: 31,
        biz_time: 0.57,
        meter_charge_time: 1.3,
        biz_dist_time: 1.1,
        dispatcher_cnt: 3,
        base_pay: 8720,
        year_of_service: 4,
        year_of_service_pay: 8000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 693873,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 23790,
        care_insurance: 5480,
        employment_insurance: 2047,
        advance_payment: 47900,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 255893,
        total_deduction: 79217,
        total_salary: 176676 },
      { in_date: '202111',
        emp_no: 196,
        emp_name_kr: '박경식',
        emp_identi: '560825-1684233',
        position_name: '정규기사',
        emp_stt_date: '2017-09-01',
        vehicle_license_no: 27312134,
        vehicle_license_req_no: '대구31바2134',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 111,
        meter_charge: 3185000,
        biz_dist: 3288,
        biz_time: 97.45,
        meter_charge_time: 85.7,
        biz_dist_time: 119.6,
        dispatcher_cnt: 2,
        base_pay: 967920,
        year_of_service: 4,
        year_of_service_pay: 8000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 83250,
        remuneration_amount: 1051208,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 36050,
        care_insurance: 8300,
        employment_insurance: 10387,
        advance_payment: 3185000,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1298343,
        total_deduction: 3239737,
        total_salary: -1941394 },
      { in_date: '202111',
        emp_no: 249,
        emp_name_kr: '우영조',
        emp_identi: '550303-1789711',
        position_name: '정규기사',
        emp_stt_date: '2018-03-01',
        vehicle_license_no: 27357352,
        vehicle_license_req_no: '대구35바7352',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 45,
        meter_charge: 1329800,
        biz_dist: 964,
        biz_time: 52.36,
        meter_charge_time: 35.8,
        biz_dist_time: 35.1,
        dispatcher_cnt: 1,
        base_pay: 392400,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 1,
        weekly_pay: 59794,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 717257,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 24600,
        care_insurance: 5660,
        employment_insurance: 3666,
        advance_payment: 1329800,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 458194,
        total_deduction: 1363726,
        total_salary: -905532 },
      { in_date: '202111',
        emp_no: 193,
        emp_name_kr: '박진환',
        emp_identi: '561228-1673617',
        position_name: '정규기사',
        emp_stt_date: '2018-01-01',
        vehicle_license_no: 27312107,
        vehicle_license_req_no: '대구31바2107',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 26,
        meter_charge: 856900,
        biz_dist: 583,
        biz_time: 26.33,
        meter_charge_time: 23.1,
        biz_dist_time: 21.2,
        dispatcher_cnt: 12,
        base_pay: 226720,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 0,
        weekly_pay: 0,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 490732,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 16830,
        care_insurance: 3860,
        employment_insurance: 1862,
        advance_payment: 856900,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 232720,
        total_deduction: 879452,
        total_salary: -646732 },
      { in_date: '202111',
        emp_no: 221,
        emp_name_kr: '이유곤',
        emp_identi: '600406-1794113',
        position_name: '정규기사',
        emp_stt_date: '2018-03-21',
        vehicle_license_no: 27312106,
        vehicle_license_req_no: '대구31바2106',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 71,
        meter_charge: 2302100,
        biz_dist: 1568,
        biz_time: 75.35,
        meter_charge_time: 61.9,
        biz_dist_time: 57,
        dispatcher_cnt: 7,
        base_pay: 619120,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 2,
        weekly_pay: 119587,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 568712,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 19500,
        care_insurance: 4480,
        employment_insurance: 5958,
        advance_payment: 2302100,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 744707,
        total_deduction: 2332038,
        total_salary: -1587331 },
      { in_date: '202111',
        emp_no: 224,
        emp_name_kr: '정석금',
        emp_identi: '651124-1769914',
        position_name: '정규기사',
        emp_stt_date: '2018-08-22',
        vehicle_license_no: 27312127,
        vehicle_license_req_no: '대구31바2127',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 58,
        meter_charge: 1987700,
        biz_dist: 1467,
        biz_time: 50.35,
        meter_charge_time: 53.5,
        biz_dist_time: 53.4,
        dispatcher_cnt: 26,
        base_pay: 505760,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 0,
        weekly_pay: 0,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 428727,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 18940,
        health_insurance: 14700,
        care_insurance: 3380,
        employment_insurance: 4094,
        advance_payment: 1987700,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 511760,
        total_deduction: 2028814,
        total_salary: -1517054 },
      { in_date: '202111',
        emp_no: 246,
        emp_name_kr: '최철은',
        emp_identi: '580512-1670411',
        position_name: '정규기사',
        emp_stt_date: '2018-11-05',
        vehicle_license_no: 27312137,
        vehicle_license_req_no: '대구31바2137',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 23,
        meter_charge: 711300,
        biz_dist: 520,
        biz_time: 24.7,
        meter_charge_time: 19.1,
        biz_dist_time: 18.9,
        dispatcher_cnt: 3,
        base_pay: 200560,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 1439328,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 49360,
        care_insurance: 11360,
        employment_insurance: 3566,
        advance_payment: 711300,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 445733,
        total_deduction: 775586,
        total_salary: -329853 },
      { in_date: '202111',
        emp_no: 186,
        emp_name_kr: '이호준',
        emp_identi: '600707-1691611',
        position_name: '정규기사',
        emp_stt_date: '2018-01-24',
        vehicle_license_no: 27317302,
        vehicle_license_req_no: '대구31바7302',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 80,
        meter_charge: 2908300,
        biz_dist: 2182,
        biz_time: 83.51,
        meter_charge_time: 78.2,
        biz_dist_time: 79.3,
        dispatcher_cnt: 27,
        base_pay: 697600,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 3,
        weekly_pay: 179380,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 736527,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 25260,
        care_insurance: 5800,
        employment_insurance: 7064,
        advance_payment: 2908300,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 882980,
        total_deduction: 2946424,
        total_salary: -2063444 },
      { in_date: '202111',
        emp_no: 199,
        emp_name_kr: '정길호',
        emp_identi: '680323-1796028',
        position_name: '정규기사',
        emp_stt_date: '2018-01-25',
        vehicle_license_no: 27317303,
        vehicle_license_req_no: '대구31바7303',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 82,
        meter_charge: 2932800,
        biz_dist: 2266,
        biz_time: 83.53,
        meter_charge_time: 78.9,
        biz_dist_time: 82.4,
        dispatcher_cnt: 3,
        base_pay: 715040,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 2,
        weekly_pay: 119587,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 562723,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 24880,
        health_insurance: 19300,
        care_insurance: 4440,
        employment_insurance: 6725,
        advance_payment: 2932800,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 840627,
        total_deduction: 2988145,
        total_salary: -2147518 },
      { in_date: '202111',
        emp_no: 225,
        emp_name_kr: '서헌교',
        emp_identi: '520207-1029717',
        position_name: '정규기사',
        emp_stt_date: '2018-09-04',
        vehicle_license_no: 27317335,
        vehicle_license_req_no: '대구31바7335',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 91,
        meter_charge: 3055600,
        biz_dist: 2445,
        biz_time: 101.4,
        meter_charge_time: 82.2,
        biz_dist_time: 88.9,
        dispatcher_cnt: 3,
        base_pay: 793520,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 25020,
        remuneration_amount: 758415,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 26010,
        care_insurance: 5980,
        employment_insurance: 8510,
        advance_payment: 3055600,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1063713,
        total_deduction: 3096100,
        total_salary: -2032387 },
      { in_date: '202111',
        emp_no: 200,
        emp_name_kr: '권동역',
        emp_identi: '500308-1690319',
        position_name: '정규기사',
        emp_stt_date: '2018-04-01',
        vehicle_license_no: 27312103,
        vehicle_license_req_no: '대구31바2103',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 109,
        meter_charge: 3261100,
        biz_dist: 2652,
        biz_time: 113.3,
        meter_charge_time: 87.7,
        biz_dist_time: 96.4,
        dispatcher_cnt: 24,
        base_pay: 950480,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 117495,
        remuneration_amount: 774111,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 26550,
        care_insurance: 6100,
        employment_insurance: 10505,
        advance_payment: 3261100,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1313148,
        total_deduction: 3304255,
        total_salary: -1991107 },
      { in_date: '202111',
        emp_no: 198,
        emp_name_kr: '이승주',
        emp_identi: '750103-1524312',
        position_name: '정규기사',
        emp_stt_date: '2018-10-24',
        vehicle_license_no: 27312138,
        vehicle_license_req_no: '대구31바2138',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 96,
        meter_charge: 3496700,
        biz_dist: 2813,
        biz_time: 91.17,
        meter_charge_time: 94.1,
        biz_dist_time: 102.3,
        dispatcher_cnt: 28,
        base_pay: 837120,
        year_of_service: 3,
        year_of_service_pay: 6000,
        weekly_cnt: 3,
        weekly_pay: 179380,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 223515,
        remuneration_amount: 655702,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 28980,
        health_insurance: 22490,
        care_insurance: 5180,
        employment_insurance: 9968,
        advance_payment: 3496700,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1246015,
        total_deduction: 3563318,
        total_salary: -2317303 },
      { in_date: '202111',
        emp_no: 232,
        emp_name_kr: '박무준',
        emp_identi: '730514-1671324',
        position_name: '정규기사',
        emp_stt_date: '2019-03-01',
        vehicle_license_no: 27312120,
        vehicle_license_req_no: '대구31바2120',
        fuel_type: '001',
        fuel_name: 'LPG',
        deposit_tot_amount: 0,
        working_hours: 86,
        meter_charge: 3001500,
        biz_dist: 2480,
        biz_time: 87.7,
        meter_charge_time: 80.7,
        biz_dist_time: 90.2,
        dispatcher_cnt: 28,
        base_pay: 749920,
        year_of_service: 2,
        year_of_service_pay: 4000,
        weekly_cnt: 3,
        weekly_pay: 179380,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 675,
        remuneration_amount: 741975,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 32800,
        health_insurance: 25440,
        care_insurance: 5860,
        employment_insurance: 7472,
        advance_payment: 3001500,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 933975,
        total_deduction: 3073072,
        total_salary: -2139097 },
      { in_date: '202111',
        emp_no: 240,
        emp_name_kr: '안구혁',
        emp_identi: '701211-1684321',
        position_name: '정규기사',
        emp_stt_date: '2019-10-30',
        vehicle_license_no: 2112,
        vehicle_license_req_no: '대구31바2112',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 34,
        meter_charge: 1090900,
        biz_dist: 875,
        biz_time: 32.24,
        meter_charge_time: 29.3,
        biz_dist_time: 31.8,
        dispatcher_cnt: 0,
        base_pay: 296480,
        year_of_service: 2,
        year_of_service_pay: 4000,
        weekly_cnt: 0,
        weekly_pay: 0,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 951644,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 42120,
        health_insurance: 32640,
        care_insurance: 7520,
        employment_insurance: 2404,
        advance_payment: 1090900,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 300480,
        total_deduction: 1175584,
        total_salary: -875104 },
      { in_date: '202111',
        emp_no: 241,
        emp_name_kr: '황선식',
        emp_identi: '680225-1673719',
        position_name: '정규기사',
        emp_stt_date: '2019-11-27',
        vehicle_license_no: 27317320,
        vehicle_license_req_no: '대구31바7320',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 76,
        meter_charge: 2411700,
        biz_dist: 1845,
        biz_time: 74.39,
        meter_charge_time: 64.9,
        biz_dist_time: 67.1,
        dispatcher_cnt: 1,
        base_pay: 662720,
        year_of_service: 2,
        year_of_service_pay: 4000,
        weekly_cnt: 1,
        weekly_pay: 59794,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 0,
        remuneration_amount: 632408,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 27990,
        health_insurance: 21690,
        care_insurance: 4980,
        employment_insurance: 5812,
        advance_payment: 2411700,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 726514,
        total_deduction: 2472172,
        total_salary: -1745658 },
      { in_date: '202111',
        emp_no: 4597,
        emp_name_kr: '하문수',
        emp_identi: '580228-1326549',
        position_name: null,
        emp_stt_date: '2021-10-01',
        vehicle_license_no: 7348,
        vehicle_license_req_no: '대구31바7348',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 126,
        meter_charge: 4278100,
        biz_dist: 3215,
        biz_time: 112.3,
        meter_charge_time: 115.1,
        biz_dist_time: 116.9,
        dispatcher_cnt: 0,
        base_pay: 1098720,
        year_of_service: 0,
        year_of_service_pay: 0,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 575145,
        remuneration_amount: 0,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 0,
        care_insurance: 0,
        employment_insurance: 15304,
        advance_payment: 4278100,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 1913038,
        total_deduction: 4293404,
        total_salary: -2380366 },
      { in_date: '202111',
        emp_no: 15,
        emp_name_kr: '강찬수',
        emp_identi: '123456-3154697',
        position_name: null,
        emp_stt_date: '2021-10-01',
        vehicle_license_no: 27312146,
        vehicle_license_req_no: '대구31바2146',
        fuel_type: '005',
        fuel_name: '전기',
        deposit_tot_amount: 0,
        working_hours: 216,
        meter_charge: 7193200,
        biz_dist: 5393,
        biz_time: 199.5,
        meter_charge_time: 193.5,
        biz_dist_time: 196.1,
        dispatcher_cnt: 27,
        base_pay: 1883520,
        year_of_service: 0,
        year_of_service_pay: 0,
        weekly_cnt: 4,
        weekly_pay: 239173,
        holiday_work_pay: 0,
        holiday_with_pay: 0,
        holiday_cnt: 0,
        holiday_pay: 0,
        bonus: 1886940,
        remuneration_amount: 0,
        income_tax: 0,
        resident_tax: 0,
        national_pension: 0,
        health_insurance: 0,
        care_insurance: 0,
        employment_insurance: 32077,
        advance_payment: 7193200,
        deductible_income_tax: 0,
        deductible_local_income_tax: 0,
        advance_tot_amount: 0,
        carry_over_pay: 0,
        health_insurance_payment: 0,
        total_payment: 4009633,
        total_deduction: 7225277,
        total_salary: -3215644 } ]

        let borderStyles = {
            top: { style: "thin" },
            left: { style: "thin" },
            bottom: { style: "thin" },
            right: { style: "thin" }
          };
        workSheet.eachSheet((sheet) => {
            sheet.eachRow({ includeEmpty: true }, function (row, rowNumber) {
                // console.log("Row " + rowNumber + " = " + JSON.stringify(row.values));
                // console.log(row.)
                if (rowNumber==2){
                    row.values = [,"2022년 04월분 급여지급명세서",,,,,,,,,,,"결재","팀장","과장","부장","이사","사장"]
                    row.getCell(1).font = {size:20, underline: "double"}
                    row.getCell(12).border = borderStyles;
                    row.getCell(13).border = borderStyles;
                    row.getCell(14).border = borderStyles;
                    row.getCell(15).border = borderStyles;
                    row.getCell(16).border = borderStyles;
                    row.getCell(17).border = borderStyles;
                }
                // if (rowNumber==3){
                //     // console.log("Value ::  " + row.values);
                // }
                // if (rowNumber==9){
                //     console.log(row.values);
                // }
                console.log("Value ::  " + row.values);

            });
            sheet.getRow(2).alignment ={vertical: 'middle', horizontal: 'center'};
            sheet.getRow(3).alignment ={vertical: 'middle', horizontal: 'center'};
            sheet.getRow(4).alignment ={vertical: 'middle', horizontal: 'center'};
            let cnt =1;
            for(var item of mokData){
                // console.log(item);

                let tempRowValue = [ ,
                    cnt,
                    `${item['emp_no']}\n${item['emp_name_kr']} \n${item['position_name']}`,
                    `${item['emp_stt_date']}\n\n${item['year_of_service']}`,
                    `${item['deposit_tot_amount'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n\n${item['working_hours']}`,
                    `${item['meter_charge'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['biz_dist']}\n${item['biz_time']}`,
                    `${item['meter_charge_time']}\n${item['biz_dist_time']}\n${item['dispatcher_cnt']}`,
                    `${item['working_hours']}\n${item['year_of_service']}\n${item['weekly_cnt']}`,
                    `${item['base_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['year_of_service_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['weekly_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}`,
                    `0\n0\n${item['holiday_cnt']}`,
                    `${item['holiday_work_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['holiday_with_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['holiday_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}`,
                    `${item['bonus'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n\n`,
                    ,
                    `${item['income_tax'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['resident_tax'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['national_pension'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}`,
                    `${item['health_insurance'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['care_insurance'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['employment_insurance']}`,
                    `${item['advance_payment'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['deductible_income_tax'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['deductible_local_income_tax']}`,
                    `${item['advance_tot_amount'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['carry_over_pay'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['health_insurance_payment'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}`,
                    `${item['total_payment'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['total_deduction'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}\n${item['total_salary'].toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ",")}` 
                ]

                cnt++
                sheet.addRow(tempRowValue,'i+')
            }

            console.log("row ", sheet.rowCount);
            // for(let i=9; i<=sheet.rowCount; i++){
            //     sheet.getRow(i).alignment ={vertical: 'middle', horizontal: 'center', wrapText: true};
            //     sheet.getRow(i).border = borderStyles;
            // }
        });
        // console.log(rows[''])

        res.setHeader(
        "Content-Type",
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        );
        res.setHeader(
        "Content-Disposition",
        "attachment; filename=" + "salary.xlsx"
        ); 
        

        return await workbook.xlsx.write(res).then(
            function(){
                res.status(200).end()
            }
        )

    },
};

module.exports = excel;
